services:
  - type: web
    name: api-testing-poc
    runtime: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: SECRET_KEY
        generateValue: true
